In [7]:
import numpy as np
import importlib
from sklearn.datasets import make_classification

In [8]:
X,y=make_classification(n_samples=1000, n_features=10, n_informative=3, n_redundant=5, random_state=42)
y=2*y-1

In [63]:
import src.OptimizedCuttingPlaneSVM as ocpsvm

In [70]:
importlib.reload(ocpsvm)

<module 'src.OptimizedCuttingPlaneSVM' from 'C:\\Users\\18pep\\Documents\\sem_I\\OmiDA\\Project\\src\\OptimizedCuttingPlaneSVM.py'>

In [71]:
model=ocpsvm.OCPSVM()

In [77]:
np.mean(X,axis=0)

array([ 0.15110451, -0.17071388, -0.50186355,  0.72659273, -0.52936132,
        0.00948628,  0.4820599 ,  0.24641531, -0.00303309, -0.00403843])

In [78]:
model.W

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [132]:
A=np.array([[1,2],[3,4],[5,6]])
b=np.array([1,-1,1])

In [136]:
(A.T*b).T

array([[ 1,  2],
       [-3, -4],
       [ 5,  6]])

In [18]:
a=np.array([1,2,3])
b=np.array([0,0,0])

In [19]:
np.linalg.norm(a-b,2)**2

np.float64(14.0)

In [26]:
A=np.array([[1,2],[3,4],[5,6]])

In [58]:
A=np.hstack((A,np.array([1,1,1]).reshape(-1,1)))

In [61]:
for a in A:
    print(a)

[1 2 1]
[0 4 1]
[5 0 1]


In [62]:
A

array([[1, 2, 1],
       [0, 4, 1],
       [5, 0, 1]])